general {
    grab_focus = 1
    show_apps_on_open = 1
}

cache {
    enabled = 1
}

finders {
    default_finder = desktop
    desktop_prefix =
    unicode_prefix = .
    math_prefix = =
}

ui {
    window_size = 600 450
}
